Import('env')

env.Append (CPPPATH='#')

env.Command ('table.cpp', 'tablegen.py', '$MY_PYTHON $SOURCE > $TARGET')

env.StaticLibrary('statlib', 
    # This adds fPIC in a portable way
    SharedObject (['StaticLibrarySource.cpp','table.cpp']))
