from waflib.Task import Task
import sys

class tablegen(Task):
    def run(self):
        return self.exec_command ('python {} > {}'.format (
            self.inputs [0].abspath (),
            self.outputs [0].abspath ()
        ))

def options (opt):
    opt.load ('compiler_cxx')

def configure (conf):
    conf.load ('compiler_cxx')

def build (ctx):
    tg = tablegen (env=ctx.env)
    tg.set_inputs (ctx.path.find_resource ('tablegen.py'))
    tg.set_outputs (ctx.path.find_or_declare ('table.cpp'))

    ctx.add_to_group(tg)
    ctx.stlib (
        source = 'StaticLibrarySource.cpp table.cpp',
        includes = '.',
        export_includes = '.',
        target = 'statlib', 
        cxxflags=ctx.env.CXXFLAGS_cxxshlib)
